#!/usr/bin/env bash

# `.exports` is used to provide custom variables.
#
# This file is used as a part of `.shell/env`


# === History params ===

export HISTSIZE=10000
export HISTFILESIZE=10000


# === PATH modifications ===

# Adds `poetry` binary, should be added to the end:
PATH="$HOME/.poetry/bin:$PATH"

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
PATH="$PYENV_ROOT/bin:$PATH"

export PATH


# === General ===

# Homebrew:
export HOMEBREW_NO_ANALYTICS=1  # disables statistics that brew collects


# === Code highlight ===
# https://github.com/zsh-users/zsh-syntax-highlighting

# We won't highlight code longer than 200 chars, because it is slow:
export ZSH_HIGHLIGHT_MAXLENGTH=200
