#!/usr/bin/env bash

# `external` handles all external tools.
#
# This file is used as a part of `.shell/env`

# === Linux ===
if [[ `uname` != Darwin ]]; then
  if [ $(command -v pyenv) ]; then
    eval "$(pyenv init --path)"
    eval "$(pyenv virtualenv-init -)"
  fi
fi


# === MacOS ===
if [[ `uname` = Darwin ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi
