#!/usr/bin/env bash

# `external` handles all external tools.
#
# This file is used as a part of `.shell/env`

# === Version managers ===
if [ $(command -v pyenv) ]; then
  if [[ `uname` = Darwin ]]; then
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
  else
    eval "$(pyenv init --path)"
    eval "$(pyenv virtualenv-init -)"
  fi
fi
