#!/usr/bin/env bash

set -e

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASE_DIR}"
git submodule update --init --recursive --remote


META_DIR="meta"

BASE_CONFIGURATOR="${BASE_DIR}/${META_DIR}/base.yaml"

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"


for config in ${@}; do
    # create temporary file
    configFile="$(mktemp)"
    suffix="-sudo"
    CONFIGURATOR="${BASE_DIR}/${META_DIR}/configurators/${config%"$suffix"}.yaml"

    echo -e "$(<$BASE_CONFIGURATOR)\n$(<$CONFIGURATOR)" > "$configFile"

    cmd=("${BASE_DIR}/${META_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" -c "$configFile")

    if [[ $config == *"sudo"* ]]; then
        cmd=(sudo "${cmd[@]}")
    fi

    "${cmd[@]}"
    rm -f "$configFile"
done

cd "${BASE_DIR}"
