- defaults:
    link:
      relink: true
    shell:
      quiet: true
      stdout: true
      stderr: true
    brewfile:
      no-upgrade: true
      stdout: true
      stderr: true
    yum:
      sudo: True
      stdout: true
      stderr: false

- clean: ["~"]
